# Generated by Django 5.0 on 2023-12-23 17:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_alter_taskmodel_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taskmodel",
            name="user",
        ),
    ]
