# Generated by Django 5.0 on 2023-12-24 19:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0004_taskmodel_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="task_images/"),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="taskmodel",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 12, 24, 19, 37, 10, 212747, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AddField(
            model_name="taskmodel",
            name="image",
            field=models.ManyToManyField(blank=True, null=True, to="tasks.taskimages"),
        ),
    ]
