# Generated by Django 5.0 on 2023-12-25 04:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0006_alter_taskmodel_created_remove_taskmodel_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskmodel",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 12, 25, 4, 52, 17, 933923, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
